Added a view entity for customer feed.
hotwax/mantle-netsuite-connector pull request #7
Opened 2024-12-27 13:39 UTC by Shinde-nutan

Todo: added description

2024-12-31 03:28 UTC, dt2patel requested changes

2024-12-31 03:28 UTC, dt2patel commented on entity/NetsuiteCustomer.xml
> +                <econdition field-name="partyIdentificationTypeId" operator="equals" value="SHOPIFY_CUST_ID"/>
we need a way to make the party identification included in the feed a selectable parameter or this should go in the groovy script. I think partyIdentificationTypes should be a list that can be passed into the main service. Then we can have a wrapper specifically for syncing Shopify customers to NS.

2024-12-31 03:28 UTC, dt2patel commented on entity/NetsuiteCustomer.xml
> +                <date-filter/>
why do we have a date filter here?

2025-01-02 07:18 UTC, Shinde-nutan commented on entity/NetsuiteCustomer.xml
> +                <date-filter/>
The date filter is need to fetch the valid contact mech in case we have two or more records in the associated with same party with from date and thru date set on it. 

we generally add the date filter on those entity where we have the from date and thru date fields.

2025-01-15 05:58 UTC, merged