Added a service to generate the customer feed from hotwax to Netsuite.
hotwax/mantle-netsuite-connector pull request #8
Opened 2024-12-28 14:22 UTC by Shinde-nutan

Todo: Add the description

2024-12-30 06:26 UTC, dixitdeepak commented on service/co/hotwax/netsuite/NetsuiteCustomerService.xml
> +                        customerList.add(customerData)
It's not good practice to keep all data in memory and then write to file. This will cause performance issue, 
Instead you should write data to file.

2024-12-31 03:41 UTC, dt2patel requested changes

2024-12-31 03:41 UTC, dt2patel commented on service/co/hotwax/netsuite/NetsuiteCustomerService.xml
> +            <!--TODO: Here currently the view used to get the eligible orders for the create feed does not have the shipment method
eligible orders?

2024-12-31 03:41 UTC, dt2patel commented on service/co/hotwax/netsuite/NetsuiteCustomerService.xml
> +                        customerList.add(customerData)
So as each customer is iterated, we should be writing to file. Correct? @dixitdeepak

2024-12-31 03:41 UTC, dt2patel commented on service/co/hotwax/netsuite/NetsuiteCustomerService.xml
> +            <!-- Save the Json Feed File path in System Message messageText -->
```suggestion
            <!-- Save the CSV Feed File path in System Message messageText -->
```

2024-12-31 05:39 UTC, dixitdeepak commented on service/co/hotwax/netsuite/NetsuiteCustomerService.xml
> +                        customerList.add(customerData)
We should use writer to write data for each row, there are various ways to write large data in file using writer stream.

2025-01-15 09:41 UTC, merged